CREATE OR REPLACE TABLE PLATFORM_DB.METADATA.ENTITY_CONFIG (
  ENTITY_NAME STRING,
  LANDING_TABLE STRING,
  BUSINESS_KEY STRING,
  ACTIVE BOOLEAN
);

INSERT OVERWRITE INTO PLATFORM_DB.METADATA.ENTITY_CONFIG (ENTITY_NAME, LANDING_TABLE, BUSINESS_KEY, ACTIVE)
VALUES
  ('USERS', 'PLATFORM_DB.LANDING.LANDING_USERS', 'ID', TRUE),
  ('POSTS', 'PLATFORM_DB.LANDING.LANDING_POSTS', 'ID', TRUE);
