CREATE OR REPLACE PIPE PLATFORM_DB.INGESTION.PIPE_INGEST_POSTS
AUTO_INGEST = TRUE
AS
COPY INTO PLATFORM_DB.LANDING.LANDING_POSTS (payload, source_filename, source_row_number)
FROM (
  SELECT
    $1,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER
  FROM @PLATFORM_DB.LANDING.LANDING_STAGE/posts/
)
FILE_FORMAT = (TYPE = JSON);
