CREATE OR REPLACE STREAM PLATFORM_DB.INGESTION.landing_users_stream
ON TABLE PLATFORM_DB.LANDING.LANDING_USERS;

CREATE OR REPLACE STREAM PLATFORM_DB.INGESTION.landing_posts_stream
ON TABLE PLATFORM_DB.LANDING.LANDING_POSTS;
