CREATE OR REPLACE STREAM PLATFORM_DB.INGESTION.landing_users_stream
ON TABLE PLATFORM_DB.INGESTION.LANDING_USERS;

CREATE OR REPLACE STREAM PLATFORM_DB.INGESTION.landing_posts_stream
ON TABLE PLATFORM_DB.INGESTION.LANDING_POSTS;
