CREATE DATABASE IF NOT EXISTS PLATFORM_DB;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DB.INGESTION;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DB.METADATA;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DB.DV_RAW;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DB.PROCESSING;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DB.ORCHESTRATION;

