USE DATABASE PLATFORM_DB;
USE SCHEMA INGESTION;

CREATE OR REPLACE FILE FORMAT json_ff
TYPE = JSON;

CREATE OR REPLACE STAGE LANDING_STAGE
URL = 'gcs://slalom-demo-gcp/landing/'
STORAGE_INTEGRATION = gcs_int
FILE_FORMAT = json_ff;

LIST @LANDING_STAGE;
