USE DATABASE PLATFORM_DB;
USE SCHEMA LANDING;

CREATE OR REPLACE TABLE LANDING_USERS (
    payload VARIANT,
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    filename STRING,
    file_row_number NUMBER
);

CREATE OR REPLACE TABLE LANDING_POSTS (
    payload VARIANT,
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    filename STRING,
    file_row_number NUMBER
);
