USE DATABASE PLATFORM_DB;
USE SCHEMA INGESTION;

CREATE OR REPLACE PIPE PIPE_INGEST_USERS
AS
COPY INTO PLATFORM_DB.LANDING.LANDING_USERS
(
    payload,
    filename,
    file_row_number
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @LANDING_STAGE/users
)
FILE_FORMAT = (TYPE = JSON);

ALTER PIPE PIPE_INGEST_USERS REFRESH;

CREATE OR REPLACE PIPE PIPE_INGEST_POSTS
AS
COPY INTO PLATFORM_DB.LANDING.LANDING_POSTS
(
    payload,
    filename,
    file_row_number
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @LANDING_STAGE/posts
)
FILE_FORMAT = (TYPE = JSON);

ALTER PIPE PIPE_INGEST_POSTS REFRESH;
