-- Purpose:
-- Create and resume orchestration tasks that trigger processing procedures from stream availability.
-- Dependencies:
-- - PLATFORM_DB.ORCHESTRATION schema exists.
-- - PLATFORM_DB.PROCESSING.SP_PROCESS_USERS and PLATFORM_DB.PROCESSING.SP_PROCESS_POSTS procedures exist.
-- - PLATFORM_DB.INGESTION.LANDING_USERS_STREAM and PLATFORM_DB.INGESTION.LANDING_POSTS_STREAM streams exist.
-- Execution order:
-- 1) Run after streams and stored procedures are created.
-- 2) Resume tasks after creation.

CREATE OR REPLACE TASK PLATFORM_DB.ORCHESTRATION.TASK_PROCESS_USERS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('PLATFORM_DB.INGESTION.LANDING_USERS_STREAM')
AS
CALL PLATFORM_DB.PROCESSING.SP_PROCESS_USERS();

CREATE OR REPLACE TASK PLATFORM_DB.ORCHESTRATION.TASK_PROCESS_POSTS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('PLATFORM_DB.INGESTION.LANDING_POSTS_STREAM')
AS
CALL PLATFORM_DB.PROCESSING.SP_PROCESS_POSTS();

ALTER TASK PLATFORM_DB.ORCHESTRATION.TASK_PROCESS_USERS RESUME;
ALTER TASK PLATFORM_DB.ORCHESTRATION.TASK_PROCESS_POSTS RESUME;
